language: python
python:
- '2.7'
services:
  - mongodb
install:
  - pip install -r requirements.txt --allow-all-external
  - pip install --upgrade numpy
env:
  -DJANGO=1.8
before_script:
  - ./lint.sh
script:
  - python agiliqcom/manage.py test blogango agiliqpages dinette graphosdemo parsley parsleydemo --settings=settings.test

