language: python
python:
  - "2.7"
# command to install dependencies
cache:
  directories:
    - $HOME/.pip-cache/
    - /home/travis/virtualenv/python2.7

install: "pip install -r requirements.txt --allow-all-external"
env:
    DJANGO_SECRET_KEY=travis
# command to run tests
before_script:
  - ./lint.sh
script:
  -  python agiliqcom/manage.py test agiliqpages blogango --settings=agiliqcom.settings.test
