language: python
python:
- '2.7'
services:
  - mongodb
install:
  - pip install -r requirements.txt --allow-all-external
env:
  -DJANGO=1.8
before_script:
- ./lint.sh
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bundle exec rake tests:integration || false'
- python agiliqcom/manage.py test blogango agiliqpages dinette graphosdemo parsley parsleydemo --settings=settings.test

