language: python
python:
- '2.7'
services:
  - mongodb
cache:
  directories:
  - $HOME/.pip-cache/
  - /home/travis/virtualenv/python2.7
install:
  - pip install -r requirements.txt --allow-all-external --download-cache $HOME/.pip-cache
env:
  -DJANGO_SECRET_KEY=travis
before_script:
- ./lint.sh
script:
- python agiliqcom/manage.py test agiliqpages blogango dinette graphosdemo parsley parsleydemo --settings=settings.test

